config/routes.rb
Rails.application.routes.draw do
  resources :links
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :sexuality_labels
  resources :gender_labels
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gender_label.rb
class GenderLabel < ApplicationRecord
  def flag_url
    "/flags/gender/#{name}.png"
  end
end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/sexuality_label.rb
class SexualityLabel < ApplicationRecord
  def flag_url
    "/flags/sexuality/#{name}.png"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    render
  end
end

app/controllers/gender_labels_controller.rb
class GenderLabelsController < ApplicationController
  before_action :set_gender_label, only: %i[ show edit update destroy ]

  # GET /gender_labels or /gender_labels.json
  def index
    @gender_labels = GenderLabel.all
  end

  # GET /gender_labels/1 or /gender_labels/1.json
  def show
  end

  # GET /gender_labels/new
  def new
    @gender_label = GenderLabel.new
  end

  # GET /gender_labels/1/edit
  def edit
  end

  # POST /gender_labels or /gender_labels.json
  def create
    @gender_label = GenderLabel.new(gender_label_params)

    respond_to do |format|
      if @gender_label.save
        format.html { redirect_to gender_label_url(@gender_label), notice: "Gender label was successfully created." }
        format.json { render :show, status: :created, location: @gender_label }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gender_label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gender_labels/1 or /gender_labels/1.json
  def update
    respond_to do |format|
      if @gender_label.update(gender_label_params)
        format.html { redirect_to gender_label_url(@gender_label), notice: "Gender label was successfully updated." }
        format.json { render :show, status: :ok, location: @gender_label }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gender_label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gender_labels/1 or /gender_labels/1.json
  def destroy
    @gender_label.destroy

    respond_to do |format|
      format.html { redirect_to gender_labels_url, notice: "Gender label was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gender_label
      @gender_label = GenderLabel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gender_label_params
      params.require(:gender_label).permit(:name)
    end
end

app/controllers/links_controller.rb
class LinksController < InheritedResources::Base

  private

    def link_params
      params.require(:link).permit(:site_name, :username, :site_icon_name, :profile_url)
    end

end

app/controllers/sexuality_labels_controller.rb
class SexualityLabelsController < ApplicationController
  before_action :set_sexuality_label, only: %i[ show edit update destroy ]

  # GET /sexuality_labels or /sexuality_labels.json
  def index
    @sexuality_labels = SexualityLabel.all
  end

  # GET /sexuality_labels/1 or /sexuality_labels/1.json
  def show
  end

  # GET /sexuality_labels/new
  def new
    @sexuality_label = SexualityLabel.new
  end

  # GET /sexuality_labels/1/edit
  def edit
  end

  # POST /sexuality_labels or /sexuality_labels.json
  def create
    @sexuality_label = SexualityLabel.new(sexuality_label_params)

    respond_to do |format|
      if @sexuality_label.save
        format.html { redirect_to sexuality_label_url(@sexuality_label), notice: "Sexuality label was successfully created." }
        format.json { render :show, status: :created, location: @sexuality_label }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sexuality_label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sexuality_labels/1 or /sexuality_labels/1.json
  def update
    respond_to do |format|
      if @sexuality_label.update(sexuality_label_params)
        format.html { redirect_to sexuality_label_url(@sexuality_label), notice: "Sexuality label was successfully updated." }
        format.json { render :show, status: :ok, location: @sexuality_label }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sexuality_label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sexuality_labels/1 or /sexuality_labels/1.json
  def destroy
    @sexuality_label.destroy

    respond_to do |format|
      format.html { redirect_to sexuality_labels_url, notice: "Sexuality label was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sexuality_label
      @sexuality_label = SexualityLabel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sexuality_label_params
      params.require(:sexuality_label).permit(:name)
    end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gender_labels_helper.rb
module GenderLabelsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sexuality_labels_helper.rb
module SexualityLabelsHelper
end

app/views/application/index.html.erb
<div class="grid-x text-center">
  <h1 class="cell">Thea Sky Barnes</h1>
  <h2 class="cell">Open source advocate, professional programmer, stressed mama, and wildly unsuccessful yoga enthusiast.</h2>
  <div class="cell medium-6 callout primary gender">
    <%= render GenderLabel.all %>
  </div>
  <div class="cell medium-6 callout secondary sexuality">
    <%= render SexualityLabel.all %>
  </div>
  <div class="cell callout success links">
    <%= render Link.all %>
  </div>
</div>

app/views/gender_labels/_form.html.erb
<%= form_with(model: gender_label) do |form| %>
  <% if gender_label.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(gender_label.errors.count, "error") %> prohibited this gender_label from being saved:</h2>

      <ul>
        <% gender_label.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/gender_labels/_gender_label.html.erb
<div id="<%= dom_id gender_label %>">
  <%= gender_label.name %>
</div>

app/views/gender_labels/edit.html.erb
<h1>Editing gender label</h1>

<%= render "form", gender_label: @gender_label %>

<br>

<div>
  <%= link_to "Show this gender label", @gender_label %> |
  <%= link_to "Back to gender labels", gender_labels_path %>
</div>

app/views/gender_labels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Gender labels</h1>

<div id="gender_labels">
  <% @gender_labels.each do |gender_label| %>
    <%= render gender_label %>
    <p>
      <%= link_to "Show this gender label", gender_label %>
    </p>
  <% end %>
</div>

<%= link_to "New gender label", new_gender_label_path %>

app/views/gender_labels/new.html.erb
<h1>New gender label</h1>

<%= render "form", gender_label: @gender_label %>

<br>

<div>
  <%= link_to "Back to gender labels", gender_labels_path %>
</div>

app/views/gender_labels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @gender_label %>

<div>
  <%= link_to "Edit this gender label", edit_gender_label_path(@gender_label) %> |
  <%= link_to "Back to gender labels", gender_labels_path %>

  <%= button_to "Destroy this gender label", @gender_label, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link) do |form| %>
  <% if link.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :site_name, style: "display: block" %>
    <%= form.text_field :site_name %>
  </div>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :site_icon_name, style: "display: block" %>
    <%= form.text_field :site_icon_name %>
  </div>

  <div>
    <%= form.label :profile_url, style: "display: block" %>
    <%= form.text_field :profile_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/links/_link.html.erb
<div id="<%= dom_id link %>">
  <%= link_to "#{link.username} @ #{link.site_name}", link.profile_url %>
</div>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Show this link", @link %> |
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Links</h1>

<div id="links">
  <% @links.each do |link| %>
    <%= render link %>
    <p>
      <%= link_to "Show this link", link %>
    </p>
  <% end %>
</div>

<%= link_to "New link", new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @link %>

<div>
  <%= link_to "Edit this link", edit_link_path(@link) %> |
  <%= link_to "Back to links", links_path %>

  <%= button_to "Destroy this link", @link, method: :delete %>
</div>

app/views/sexuality_labels/_form.html.erb
<%= form_with(model: sexuality_label) do |form| %>
  <% if sexuality_label.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sexuality_label.errors.count, "error") %> prohibited this sexuality_label from being saved:</h2>

      <ul>
        <% sexuality_label.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sexuality_labels/_sexuality_label.html.erb
<div id="<%= dom_id sexuality_label %>">
  <%= sexuality_label.name %>
</div>

app/views/sexuality_labels/edit.html.erb
<h1>Editing sexuality label</h1>

<%= render "form", sexuality_label: @sexuality_label %>

<br>

<div>
  <%= link_to "Show this sexuality label", @sexuality_label %> |
  <%= link_to "Back to sexuality labels", sexuality_labels_path %>
</div>

app/views/sexuality_labels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sexuality labels</h1>

<div id="sexuality_labels">
  <% @sexuality_labels.each do |sexuality_label| %>
    <%= render sexuality_label %>
    <p>
      <%= link_to "Show this sexuality label", sexuality_label %>
    </p>
  <% end %>
</div>

<%= link_to "New sexuality label", new_sexuality_label_path %>

app/views/sexuality_labels/new.html.erb
<h1>New sexuality label</h1>

<%= render "form", sexuality_label: @sexuality_label %>

<br>

<div>
  <%= link_to "Back to sexuality labels", sexuality_labels_path %>
</div>

app/views/sexuality_labels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sexuality_label %>

<div>
  <%= link_to "Edit this sexuality label", edit_sexuality_label_path(@sexuality_label) %> |
  <%= link_to "Back to sexuality labels", sexuality_labels_path %>

  <%= button_to "Destroy this sexuality label", @sexuality_label, method: :delete %>
</div>